### ISSUE TITLE
关于 RESClient 内存泄漏问题

### ISSUE THREAD

**Issue by Garfield0308** [WangShuo1143368701/WSLiveDemo#10]
RESClient 里引用了Actvity 导致内存泄漏
![screenshot_20180326-142452](https://user-images.githubusercontent.com/16233202/37890214-4d6759e8-3102-11e8-9763-298231c4b0d0.png)

建议在RESClient.destroy()中释放activity

**Comment by WangShuo1143368701** [comment]
对 棒棒哒

**Comment by Garfield0308** [comment]
请教下，为什么要用弱应用类型来解决这个问题呢？ 而不是在destroy 做null 处理呢？
