### ISSUE TITLE
将设备强制横屏 输出的视频方向不对

### ISSUE THREAD

**Issue by lisi6996** [WangShuo1143368701/WSLiveDemo#11]

**Comment by WangShuo1143368701** [comment]
视频录制？横屏录制要修改录制的纹理坐标

**Comment by sili6996** [comment]
大佬求教 要是想要横屏录制 输出文件方向也对是修改getCamera2DTextureVerticesBuffer(final int directionFlag, final float cropRatio) 这个方法吗


     if ((directionFlag & 0xF0) == RESCoreParameters.FLAG_DIRECTION_ROATATION_0 || (directionFlag & 0xF0) == RESCoreParameters.FLAG_DIRECTION_ROATATION_180) {
            if (cropRatio > 0) {
                buffer[1] = buffer[1] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[3] = buffer[3] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[5] = buffer[5] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[7] = buffer[7] == 1.0f ? (1.0f - cropRatio) : cropRatio;
            } else {
                buffer[0] = buffer[0] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[2] = buffer[2] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[4] = buffer[4] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[6] = buffer[6] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
            }
        } else {
            if (cropRatio > 0) {
                buffer[0] = buffer[0] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[2] = buffer[2] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[4] = buffer[4] == 1.0f ? (1.0f - cropRatio) : cropRatio;
                buffer[6] = buffer[6] == 1.0f ? (1.0f - cropRatio) : cropRatio;
            } else {
                buffer[1] = buffer[1] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[3] = buffer[3] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[5] = buffer[5] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
                buffer[7] = buffer[7] == 1.0f ? (1.0f + cropRatio) : -cropRatio;
            }
        }
是这一块代码吗

**Comment by sili6996** [comment]
求大佬详细指点一二

**Comment by WangShuo1143368701** [comment]
GLDrawer2D.java 里面的

**Comment by sili6996** [comment]
谢谢大神

**Comment by lianyu-lc** [comment]
@lisi6996 兄弟，我现在需求和你一样，能指点下嘛？

**Comment by lisi6996** [comment]
如果只是输出的视频方向不对的话在MediaMuxerWrapper生成文件的时候旋转一下就好了 调用系统api setOrientationHint 如果是预览方向不对的话就需要修改纹理坐标了

**Comment by lianyu-lc** [comment]
@lisi6996 明白了，我试试看，多谢！对了，如果想要修改图片和视频的分辨率的话，你知道如何修改吗？我试了下，发现最终变形了，有点苦恼
