### ISSUE TITLE
服务器连接异常

### ISSUE THREAD

**Issue by Garfield0308** [WangShuo1143368701/WSLiveDemo#18]
连接rtmp服务器时一直重复报这个错误，而且连接不上

“ camxpipeline.cpp:1468 SendShutterNotification() pMessage->timestamp is 0, falling back to system time”

![tim 20180522100843](https://user-images.githubusercontent.com/16233202/40338541-3661267a-5da8-11e8-854c-12b34489e331.png)

**Comment by WangShuo1143368701** [comment]
你可以自己开一个流服务器试试，我博客中有讲搭建流服务器的文章
