### ISSUE TITLE
请问有64位的so库吗？在google上线应用需要64位的so库

### ISSUE THREAD

**Issue by xiaozhiaiyubao** [WangShuo1143368701/WSLiveDemo#59]

**Comment by xiaozhiaiyubao** [comment]
我尝试去修改Application文件中的 APP_ABI ，但是修改依旧不生效呢？

**Comment by xiaozhiaiyubao** [comment]
我这边通过ndk-build 生成了64位的so文件，但是在使用的过程中，遇到了问题，结束直播会闪退

**Comment by Monle** [comment]
> 我这边通过ndk-build 生成了64位的so文件，但是在使用的过程中，遇到了问题，结束直播会闪退

你可以看下是不是libresrtmp.c文件的RtmpClient_close方法的参数顺序导致的

**Comment by xiaozhiaiyubao** [comment]
可是我这边确认了一下：public static native int close(long rtmpPointer)，参数只有一个rtmpPointer

**Comment by xiaozhiaiyubao** [comment]
好的，我看了一下libresrtmp.c文件，
`
 JNIEXPORT jint JNICALL Java_me_lake_librestreaming_rtmp_RtmpClient_close
 (JNIEnv * env,jlong rtmp, jobject thiz) {
 	RTMP_Close((RTMP*)rtmp);
 	RTMP_Free((RTMP*)rtmp);
 	return 0;
 }`
是代表有两个参数的意思吗？我看java层的声明方式是：`public static native int close(long rtmpPointer)`

**Comment by xiaozhiaiyubao** [comment]
可是32位的so库，就不存在这个close方法会闪退的问题，那我需要调整参数顺序吗？把long型参数放在第一个？

**Comment by Monle** [comment]
包括libresrtmp.h中的Java_me_lake_librestreaming_rtmp_RtmpClient_close参数都要换成(JNIEnv * env,jobject thiz,jlong rtmp ) ， 然后再编译so文件就不会出问题

**Comment by xiaozhiaiyubao** [comment]
好，可是libresrtmp.h中的Java_me_lake_librestreaming_rtmp_RtmpClient_close的参数和libresrtmp.c是一样的呀
这是libresrtmp.h中的close函数：
`JNIEXPORT jint JNICALL Java_me_lake_librestreaming_rtmp_RtmpClient_close
 (JNIEnv * env,jlong rtmp, jobject thiz);`
这是libresrtmp.c中的close函数:
JNIEXPORT jint JNICALL Java_me_lake_librestreaming_rtmp_RtmpClient_close
 (JNIEnv * env,jlong rtmp, jobject thiz) {
 	RTMP_Close((RTMP*)rtmp);
 	RTMP_Free((RTMP*)rtmp);
 	return 0;
 }
这是就是原始的函数的参数设置，我现在就是不晓得应该怎么修改的参数顺序。

**Comment by Monle** [comment]
> 好，可是libresrtmp.h中的Java_me_lake_librestreaming_rtmp_RtmpClient_close的参数和libresrtmp.c是一样的呀
> 这是libresrtmp.h中的close函数：
> `JNIEXPORT jint JNICALL Java_me_lake_librestreaming_rtmp_RtmpClient_close (JNIEnv * env,jlong rtmp, jobject thiz);`
> 这是libresrtmp.c中的close函数:
> JNIEXPORT jint JNICALL Java_me_lake_librestreaming_rtmp_RtmpClient_close
> (JNIEnv * env,jlong rtmp, jobject thiz) {
> RTMP_Close((RTMP*)rtmp);
> RTMP_Free((RTMP*)rtmp);
> return 0;
> }
> 这是就是原始的函数的参数设置，我现在就是不晓得应该怎么修改的参数顺序。

都改成(JNIEnv * env,jobject thiz,jlong rtmp )

**Comment by xiaozhiaiyubao** [comment]
谢谢您，成功了，没有闪退了！太感谢了，我不太懂C，以前大学的时候学过一点点，都忘了Android JNI 这一块也是最近随着项目才看一些，真的很感谢你哦！

**Comment by kimiangel** [comment]
能把这个64的库共享出来吗?我这边也是要上架google,谢谢

**Comment by githubhuwenpeng** [comment]
你加个微信吧&nbsp; 17633905797&nbsp;我看是哪个库我下载&nbsp;下来发给你
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangShuo1143368701/WSLiveDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午3:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [WangShuo1143368701/WSLiveDemo] 请问有64位的so库吗？在google上线应用需要64位的so库 (#59)





 
能把这个64的库共享出来吗?我这边也是要上架google,谢谢

**Comment by 756230883** [comment]
能给一份so库吗  大佬们
